#!/bin/sh
# =========================================================================================
# This unix script generates random movement scenario files.
# It uses the setdest utility of ns2 to generate these files.
#
# Three files are generated with the following settings:
#   1) 25 nodes, maximum speed 5 m/s, pause time 10 sec
#   2) 100 nodes, maximum speed 5 m/s, pause time 10 sec
#   3) 200 nodes, maximum speed 5 m/s, pause time 10 sec
# =========================================================================================

clear

mkdir -p MOV_SCEN
cd MOV_SCEN

START=$(date +%s)
COUNT=0

# Simulation Parameters
X=500       # X in m
Y=500       # Y in m
T=600       # Simulation time in seconds
S=5         # Maximum speed in m/sec        
P=10        # Pause Time in sec

# Iterate over the three node count scenarios
for N in 25 100 200; do
  date | awk '{ print "Date: "$1" " $3 "-"$2"-"$6 }'
  date | awk '{ print "Time: "$4" " $5 }'
  echo " "
  echo "Creating Movement Scenario File: MOV-N${N}-S${S}-P${P} ... Please Wait !!"
  
  /opt/ns-allinone-2.35/ns-2.35/indep-utils/cmu-scen-gen/setdest/setdest \
    -v 1 -n $N -M $S -p $P -t $T -x $X -y $Y > MOV-N${N}-S${S}-P${P}
  
  echo "The Movement Scenario MOV-N${N}-S${S}-P${P} .... Done!!"
  COUNT=`expr $COUNT + 1`
  
  END=$(date +%s)
  DIFF=$(( END - START ))
  HOURS=$(( DIFF / 3600 ))
  MINUTES=$(( DIFF / 60 ))
  if [ "$MINUTES" -ge 60 ]; then
    MINUTES=$(( MINUTES % 60 ))
  fi
  
  echo "Now ${COUNT} Files Done in ${HOURS} H:${MINUTES} M"
  echo "======================================================================="
  echo " "
done

exit 0
