#!/bin/sh
# ============================================================================================
# This unix script runs scenarios on ns2 to generate trace files.
# It generates three trace files for each protocol (DSDV, DSR, AODV) and connection type (CBR)
# with the following scenarios:
#   1) 25 nodes and 15 connections
#   2) 100 nodes and 100 connections
#   3) 200 nodes and 200 connections
# ============================================================================================

FOLDER='.'
mkdir -p ./TRACE

START=$(date +%s)
COUNT=0
X=500
Y=500
T=600.1

# Loop over the protocols
for R in DSDV DSR AODV; do
  # Loop over the connection types (only CBR in this example)
  for TYPE in CBR; do
    # Loop over three predefined scenarios formatted as "nodes:connections"
    for scenario in "25:15" "100:100" "200:200"; do
      N=$(echo $scenario | cut -d: -f1)
      C=$(echo $scenario | cut -d: -f2)
      S=5
      P=10
      
      # Print date and time information
      date | awk '{ print "Date: "$1" " $3 "-"$2"-"$6 }'
      date | awk '{ print "Time: "$4" " $5 }'
      echo " "
      echo "Running trace for Protocol $R, Type $TYPE, N=$N, C=$C, S=$S, P=$P ... Please wait!"
      
      # Run the ns2 trace script using the connection and movement scenario files
      ns trace.tcl $R $TYPE $N $C $S $P $X $Y $T \
         $FOLDER/CONN_SCEN/${TYPE}-N${N}-C${C} \
         $FOLDER/MOV_SCEN/MOV-N${N}-S${S}-P${P} \
         $FOLDER/TRACE/${R}-N${N}-C${C}-S${S}-P${P}-${TYPE}.tr
      
      echo "The File ${R}-N${N}-C${C}-S${S}-P${P}-${TYPE}.tr .... Done!!"
      COUNT=`expr $COUNT + 1`
      
      # Calculate elapsed time
      END=$(date +%s)
      DIFF=$(( END - START ))
      HOURS=$(( DIFF / 3600 ))
      MINUTES=$(( (DIFF / 60) % 60 ))
      echo "Now $COUNT Files Done in $HOURS H:$MINUTES M"
      echo "======================================================================="
      echo ""
    done
  done
done

exit 0
